
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerCardConfig : ET.Object
    {
        public CrawlerCardConfig(int Id, string Name, int Cost, ET.CrawlerElement Element, ET.CrawlerCardType CardType, ET.CrawlerTargetRule TargetRule, bool Wild, bool Exhaust, int BreakLimit, string Desc)
        {
            this.Id = Id;
            this.Name = Name;
            this.Cost = Cost;
            this.Element = Element;
            this.CardType = CardType;
            this.TargetRule = TargetRule;
            this.Wild = Wild;
            this.Exhaust = Exhaust;
            this.BreakLimit = BreakLimit;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 费用
        /// </summary>
        public readonly int Cost;
        /// <summary>
        /// 五行
        /// </summary>
        public readonly ET.CrawlerElement Element;
        /// <summary>
        /// 卡牌类型
        /// </summary>
        public readonly ET.CrawlerCardType CardType;
        /// <summary>
        /// 目标规则
        /// </summary>
        public readonly ET.CrawlerTargetRule TargetRule;
        /// <summary>
        /// 是否无相牌
        /// </summary>
        public readonly bool Wild;
        /// <summary>
        /// 是否消耗
        /// </summary>
        public readonly bool Exhaust;
        /// <summary>
        /// 破势上限
        /// </summary>
        public readonly int BreakLimit;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
