
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class CrawlerStarterDeckConfigCategory : Singleton<CrawlerStarterDeckConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.CrawlerStarterDeckConfig> _dataMap;

    public CrawlerStarterDeckConfigCategory(System.Collections.Generic.Dictionary<int, ET.CrawlerStarterDeckConfig> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, ET.CrawlerStarterDeckConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.CrawlerStarterDeckConfig> DataMap => _dataMap;
    public ET.CrawlerStarterDeckConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.CrawlerStarterDeckConfig Get(int key) => _dataMap[key];
    public ET.CrawlerStarterDeckConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}
