
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// Crawlers card type
    /// </summary>
    public enum CrawlerCardType
    {
        Attack = 0,
        Defence = 1,
        Utility = 2,
        Wild = 3,
    }

}
