
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerEnemyConfig : ET.Object
    {
        public CrawlerEnemyConfig(int Id, string Name, ET.CrawlerElement Element, int MaxHp, int Attack, bool IsBoss, ET.CrawlerIntentType Intent, string Desc)
        {
            this.Id = Id;
            this.Name = Name;
            this.Element = Element;
            this.MaxHp = MaxHp;
            this.Attack = Attack;
            this.IsBoss = IsBoss;
            this.Intent = Intent;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 五行
        /// </summary>
        public readonly ET.CrawlerElement Element;
        /// <summary>
        /// 最大气血
        /// </summary>
        public readonly int MaxHp;
        /// <summary>
        /// 攻击力
        /// </summary>
        public readonly int Attack;
        /// <summary>
        /// 是否Boss
        /// </summary>
        public readonly bool IsBoss;
        /// <summary>
        /// 默认意图
        /// </summary>
        public readonly ET.CrawlerIntentType Intent;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
