
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerStarterDeckConfig : ET.Object
    {
        public CrawlerStarterDeckConfig(int Id, int DeckId, int CardId, int Count, int RuntimeCostOverride, string Desc)
        {
            this.Id = Id;
            this.DeckId = DeckId;
            this.CardId = CardId;
            this.Count = Count;
            this.RuntimeCostOverride = RuntimeCostOverride;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 牌组Id
        /// </summary>
        public readonly int DeckId;
        /// <summary>
        /// 卡牌Id
        /// </summary>
        public readonly int CardId;
        /// <summary>
        /// 数量
        /// </summary>
        public readonly int Count;
        /// <summary>
        /// 初始费用覆盖
        /// </summary>
        public readonly int RuntimeCostOverride;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
