
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerBossChantConfig : ET.Object
    {
        public CrawlerBossChantConfig(int Id, string Name, int BossEnemyId, int RemainingTurns, int ResolveDamage, ET.CrawlerElement[] BreakSlots, int VulnerableTurns, string Desc)
        {
            this.Id = Id;
            this.Name = Name;
            this.BossEnemyId = BossEnemyId;
            this.RemainingTurns = RemainingTurns;
            this.ResolveDamage = ResolveDamage;
            this.BreakSlots = BreakSlots;
            this.VulnerableTurns = VulnerableTurns;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 目标BossId
        /// </summary>
        public readonly int BossEnemyId;
        /// <summary>
        /// 倒计时回合
        /// </summary>
        public readonly int RemainingTurns;
        /// <summary>
        /// 结算伤害
        /// </summary>
        public readonly int ResolveDamage;
        /// <summary>
        /// 破势槽五行列表
        /// </summary>
        public readonly ET.CrawlerElement[] BreakSlots;
        /// <summary>
        /// 被打断虚弱回合
        /// </summary>
        public readonly int VulnerableTurns;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
