
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// Crawlers enemy intent
    /// </summary>
    public enum CrawlerIntentType
    {
        Idle = 0,
        Attack = 1,
        Defence = 2,
        Chant = 3,
        Summon = 4,
        Poison = 5,
        Disrupt = 6,
    }

}
