
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerCardEffectConfig : ET.Object
    {
        public CrawlerCardEffectConfig(int Id, int CardId, int Order, ET.CrawlerEffectType EffectType, int Value, ET.CrawlerTargetRule TargetRule, bool CanBreakChant, string Desc)
        {
            this.Id = Id;
            this.CardId = CardId;
            this.Order = Order;
            this.EffectType = EffectType;
            this.Value = Value;
            this.TargetRule = TargetRule;
            this.CanBreakChant = CanBreakChant;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 卡牌Id
        /// </summary>
        public readonly int CardId;
        /// <summary>
        /// 效果序号
        /// </summary>
        public readonly int Order;
        /// <summary>
        /// 效果类型
        /// </summary>
        public readonly ET.CrawlerEffectType EffectType;
        /// <summary>
        /// 数值
        /// </summary>
        public readonly int Value;
        /// <summary>
        /// 目标规则
        /// </summary>
        public readonly ET.CrawlerTargetRule TargetRule;
        /// <summary>
        /// 可破势
        /// </summary>
        public readonly bool CanBreakChant;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
