
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// Crawlers effect type
    /// </summary>
    public enum CrawlerEffectType
    {
        Damage = 0,
        Shield = 1,
        Draw = 2,
        GainMana = 3,
    }

}
