
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerBattleStageConfig : ET.Object
    {
        public CrawlerBattleStageConfig(int Id, string Name, int PlayerMaxHp, int MaxMana, int DrawPerTurn, int HandLimit, int StarterDeckId, int FormationId, int BossChantId, string Desc)
        {
            this.Id = Id;
            this.Name = Name;
            this.PlayerMaxHp = PlayerMaxHp;
            this.MaxMana = MaxMana;
            this.DrawPerTurn = DrawPerTurn;
            this.HandLimit = HandLimit;
            this.StarterDeckId = StarterDeckId;
            this.FormationId = FormationId;
            this.BossChantId = BossChantId;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 玩家最大气血
        /// </summary>
        public readonly int PlayerMaxHp;
        /// <summary>
        /// 灵力上限
        /// </summary>
        public readonly int MaxMana;
        /// <summary>
        /// 每回合抽牌
        /// </summary>
        public readonly int DrawPerTurn;
        /// <summary>
        /// 手牌上限
        /// </summary>
        public readonly int HandLimit;
        /// <summary>
        /// 初始牌组Id
        /// </summary>
        public readonly int StarterDeckId;
        /// <summary>
        /// 敌方阵列Id
        /// </summary>
        public readonly int FormationId;
        /// <summary>
        /// Boss吟唱Id
        /// </summary>
        public readonly int BossChantId;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
