
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class CrawlerEnemyConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(CrawlerEnemyConfigCategory);

    public ASingleton Create()
    {
        return new CrawlerEnemyConfigCategory(new System.Collections.Generic.Dictionary<int, ET.CrawlerEnemyConfig>()
        {
            [ 2001 ] = new ET.CrawlerEnemyConfig(2001, @"尸傀", ET.CrawlerElement.Earth, 35, 8, false, ET.CrawlerIntentType.Attack, @"前排低攻敌人"),
            [ 2002 ] = new ET.CrawlerEnemyConfig(2002, @"狐妖", ET.CrawlerElement.Wood, 28, 10, false, ET.CrawlerIntentType.Attack, @"前排高攻敌人"),
            [ 2099 ] = new ET.CrawlerEnemyConfig(2099, @"赤焰妖王", ET.CrawlerElement.Fire, 80, 14, true, ET.CrawlerIntentType.Chant, @"样例Boss"),
            [ 2101 ] = new ET.CrawlerEnemyConfig(2101, @"铁甲尸傀", ET.CrawlerElement.Earth, 55, 12, false, ET.CrawlerIntentType.Attack, @"高压测试敌人")
        });
    }
}
}
