
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class CrawlerBattleStageConfigCategory : Singleton<CrawlerBattleStageConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.CrawlerBattleStageConfig> _dataMap;

    public CrawlerBattleStageConfigCategory(System.Collections.Generic.Dictionary<int, ET.CrawlerBattleStageConfig> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, ET.CrawlerBattleStageConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.CrawlerBattleStageConfig> DataMap => _dataMap;
    public ET.CrawlerBattleStageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.CrawlerBattleStageConfig Get(int key) => _dataMap[key];
    public ET.CrawlerBattleStageConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}
