
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class CrawlerStageEnemyConfig : ET.Object
    {
        public CrawlerStageEnemyConfig(int Id, int FormationId, int Row, int Column, int EnemyId, string Desc)
        {
            this.Id = Id;
            this.FormationId = FormationId;
            this.Row = Row;
            this.Column = Column;
            this.EnemyId = EnemyId;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 阵列Id
        /// </summary>
        public readonly int FormationId;
        /// <summary>
        /// 行
        /// </summary>
        public readonly int Row;
        /// <summary>
        /// 列
        /// </summary>
        public readonly int Column;
        /// <summary>
        /// 敌人Id
        /// </summary>
        public readonly int EnemyId;
        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}
