
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// Crawlers target rule
    /// </summary>
    public enum CrawlerTargetRule
    {
        Self = 0,
        FrontEnemy = 1,
        FrontRow = 2,
        AllEnemies = 3,
        Boss = 4,
    }

}
