
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class CrawlerStarterDeckConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(CrawlerStarterDeckConfigCategory);

    public ASingleton Create()
    {
        return new CrawlerStarterDeckConfigCategory(new System.Collections.Generic.Dictionary<int, ET.CrawlerStarterDeckConfig>()
        {
            [ 101 ] = new ET.CrawlerStarterDeckConfig(101, 1, 1001, 2, -1, @"两张0费御剑诀"),
            [ 102 ] = new ET.CrawlerStarterDeckConfig(102, 1, 1002, 1, -1, @"一张1费防御"),
            [ 103 ] = new ET.CrawlerStarterDeckConfig(103, 1, 1003, 1, -1, @"一张2费调息牌"),
            [ 104 ] = new ET.CrawlerStarterDeckConfig(104, 1, 1004, 1, -1, @"一张3费前排伤害"),
            [ 105 ] = new ET.CrawlerStarterDeckConfig(105, 1, 1005, 1, -1, @"一张4费Boss伤害"),
            [ 106 ] = new ET.CrawlerStarterDeckConfig(106, 1, 1006, 1, -1, @"一张无相抽牌")
        });
    }
}
}
