
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class CrawlerBattleStageConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(CrawlerBattleStageConfigCategory);

    public ASingleton Create()
    {
        return new CrawlerBattleStageConfigCategory(new System.Collections.Generic.Dictionary<int, ET.CrawlerBattleStageConfig>()
        {
            [ 1 ] = new ET.CrawlerBattleStageConfig(1, @"样例秘境一", 100, 3, 5, 10, 1, 1, 1, @"当前代码内置样例参数"),
            [ 2 ] = new ET.CrawlerBattleStageConfig(2, @"高压测试", 80, 3, 5, 10, 1, 2, 1, @"提高敌人压迫用于测试回合压力")
        });
    }
}
}
