
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class CrawlerStageEnemyConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(CrawlerStageEnemyConfigCategory);

    public ASingleton Create()
    {
        return new CrawlerStageEnemyConfigCategory(new System.Collections.Generic.Dictionary<int, ET.CrawlerStageEnemyConfig>()
        {
            [ 10001 ] = new ET.CrawlerStageEnemyConfig(10001, 1, 0, 0, 2001, @"第一排左"),
            [ 10002 ] = new ET.CrawlerStageEnemyConfig(10002, 1, 0, 1, 2002, @"第一排右"),
            [ 10003 ] = new ET.CrawlerStageEnemyConfig(10003, 1, 1, 0, 2099, @"第二排Boss"),
            [ 20001 ] = new ET.CrawlerStageEnemyConfig(20001, 2, 0, 0, 2101, @"高压第一排左"),
            [ 20002 ] = new ET.CrawlerStageEnemyConfig(20002, 2, 0, 1, 2002, @"高压第一排右"),
            [ 20003 ] = new ET.CrawlerStageEnemyConfig(20003, 2, 1, 0, 2099, @"高压第二排Boss")
        });
    }
}
}
