
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class CrawlerBossChantConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(CrawlerBossChantConfigCategory);

    public ASingleton Create()
    {
        return new CrawlerBossChantConfigCategory(new System.Collections.Generic.Dictionary<int, ET.CrawlerBossChantConfig>()
        {
            [ 1 ] = new ET.CrawlerBossChantConfig(1, @"焚天妖火", 2099, 2, 35, new ET.CrawlerElement[] { ET.CrawlerElement.Water, ET.CrawlerElement.Water, ET.CrawlerElement.Earth }, 1, @"当前代码内置Boss吟唱"),
            [ 2 ] = new ET.CrawlerBossChantConfig(2, @"赤炎压制", 2099, 1, 25, new ET.CrawlerElement[] { ET.CrawlerElement.Water, ET.CrawlerElement.Earth }, 1, @"快速触发测试")
        });
    }
}
}
